In [45]:
import numpy as np
from sklearn.utils import shuffle
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from openpyxl import load_workbook

In [24]:
wb = load_workbook('Folds5x2_pp.xlsx', read_only=True)
ws = wb.get_sheet_by_name('Sheet1')
rows = [r for r in ws.iter_rows()]

In [25]:
X = np.zeros((len(rows)-1, 4))
y = np.zeros((len(rows)-1, 1))

for i, row in enumerate(rows[1:]):
    X[i] = np.array([elem.value for elem in row[:-1]])
    y[i] = row[-1].value

In [30]:
n_tr = int(y.size * 0.8)
x_test = X[n_tr:, :]
y_test = y[n_tr:, :]
x_tr = X[:n_tr, :]
y_tr = y[:n_tr :]


scaler_x = StandardScaler()
scaler_y = StandardScaler()
x_tr = scaler_x.fit_transform(x_tr)
x_test = scaler_x.transform(x_test)
y_tr = scaler_y.fit_transform(y_tr)
y_test = scaler_y.transform(y_test)

In [31]:
svm = SVR(C=10.)
svm.fit(x_tr, y_tr[:,0])

SVR(C=10.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.0,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [47]:
preds = svm.predict(x_test)
print(r2_score(y_test, preds))
print(np.sqrt(mean_squared_error(y_test, preds)))

0.942744048231
0.238012235995


In [33]:
x_tr = np.load('data/x_tr.npy')
x_te = np.load('data/x_te.npy')
y_tr = np.load('data/y_tr.npy')
y_te = np.load('data/y_te.npy')

In [36]:
scaler_x = StandardScaler()
scaler_y = StandardScaler()
x_tr = scaler_x.fit_transform(x_tr) / 3
x_te = scaler_x.transform(x_te) / 3
y_tr = scaler_y.fit_transform(y_tr)
y_te = scaler_y.transform(y_te)

In [37]:
x_te[238]

array([-0.48622388, -0.32567866,  1.11957435,  0.07335782])

In [38]:
x_te

array([[-0.58956776, -0.48432221,  0.31216444, -0.12435327],
       [ 0.18931403,  0.54253426,  0.20137639, -0.0421639 ],
       [ 0.33694814, -0.17857281, -0.23002558, -0.62776313],
       ..., 
       [ 0.5230566 ,  0.52680101, -0.02019972, -0.84031397],
       [ 0.21705135,  0.39883729,  0.03239663, -0.24877883],
       [ 0.08820703,  0.2171183 ,  0.22096014, -0.12366835]])

In [44]:
np.sum(x_tr < -1)

11

In [19]:
x_te

array([[-0.58956776, -0.48432221,  0.31216444, -0.12435327],
       [ 0.18931403,  0.54253426,  0.20137639, -0.0421639 ],
       [ 0.33694814, -0.17857281, -0.23002558, -0.62776313],
       ..., 
       [ 0.5230566 ,  0.52680101, -0.02019972, -0.84031397],
       [ 0.21705135,  0.39883729,  0.03239663, -0.24877883],
       [ 0.08820703,  0.2171183 ,  0.22096014, -0.12366835]])

In [49]:
np.min(y_tr)

-1.924085129344733